"""
Fair Comparison Chart: All Strategies from UPRO Inception (June 2009)
====================================================================
Rebases all strategies to $100K starting June 25, 2009 for fair comparison
with UPRO, since UPRO did not exist before that date.

Requires: daily_values_*.csv files generated by delta_comparison_analysis.py

Output: comparison_from_2009.png
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

import functools
print = functools.partial(print, flush=True)

_this_dir = os.path.dirname(os.path.abspath(__file__))

START_DATE = "2009-06-25"
INITIAL_CAPITAL = 100_000


def load_strategy(filename, label):
    """Load a daily_values CSV and rebase from START_DATE."""
    path = os.path.join(_this_dir, filename)
    if not os.path.exists(path):
        print(f"  WARNING: {filename} not found, skipping {label}")
        return None

    df = pd.read_csv(path)
    df["date"] = pd.to_datetime(df["date"])
    df = df[df["date"] >= START_DATE].copy()

    if len(df) == 0:
        print(f"  WARNING: No data after {START_DATE} for {label}")
        return None

    # Rebase to $100K
    first_val = df["portfolio_value"].iloc[0]
    df["portfolio_value"] = df["portfolio_value"] / first_val * INITIAL_CAPITAL

    return df


def compute_metrics(df, label):
    """Compute summary metrics for a strategy."""
    years = len(df) / 252.0
    end_val = df["portfolio_value"].iloc[-1]
    cagr = (end_val / INITIAL_CAPITAL) ** (1 / years) - 1

    daily_rets = df["portfolio_value"].pct_change().dropna()
    sharpe = (daily_rets.mean() / daily_rets.std()) * np.sqrt(252) if daily_rets.std() > 0 else 0

    downside = daily_rets[daily_rets < 0]
    sortino = (daily_rets.mean() / downside.std()) * np.sqrt(252) if len(downside) > 0 and downside.std() > 0 else 0

    cummax = df["portfolio_value"].cummax()
    drawdown = df["portfolio_value"] / cummax - 1
    max_dd = drawdown.min()

    return {
        "label": label,
        "end_val": end_val,
        "cagr": cagr,
        "sharpe": sharpe,
        "sortino": sortino,
        "max_dd": max_dd,
    }


def main():
    print("=" * 80)
    print("Fair Comparison: All Strategies from UPRO Inception (2009-06-25)")
    print("=" * 80)

    # Define strategies to load
    strategies = [
        ("daily_values_SPY_B&H.csv", "SPY B&H"),
        ("daily_values_SSO_B&H.csv", "SSO B&H"),
        ("daily_values_UPRO_B&H.csv", "UPRO B&H"),
        ("daily_values_50-Delta.csv", "50-Delta"),
        ("daily_values_55-Delta.csv", "55-Delta"),
        ("daily_values_60-Delta.csv", "60-Delta"),
        ("daily_values_70-Delta.csv", "70-Delta"),
        ("daily_values_80-Delta.csv", "80-Delta"),
        ("daily_values_90-Delta.csv", "90-Delta"),
        ("daily_values_95-Delta.csv", "95-Delta"),
    ]

    loaded = {}
    metrics = []

    print("\nLoading strategies...")
    for filename, label in strategies:
        df = load_strategy(filename, label)
        if df is not None:
            loaded[label] = df
            m = compute_metrics(df, label)
            metrics.append(m)
            print(f"  {label:<12}: ${m['end_val']:>12,.0f} | CAGR: {m['cagr']:>+6.1%} | Sharpe: {m['sharpe']:.2f} | Sortino: {m['sortino']:.2f} | Max DD: {m['max_dd']:.1%}")

    if not loaded:
        print("\nERROR: No strategy data found. Run delta_comparison_analysis.py first.")
        return

    # Sort metrics by end value descending
    metrics.sort(key=lambda x: x["end_val"], reverse=True)

    # Print summary table
    print("\n" + "=" * 90)
    print(f"SUMMARY: $100K from {START_DATE} (sorted by end value)")
    print("=" * 90)
    print(f"\n{'Strategy':<12} {'End Value':>14} {'CAGR':>10} {'Sharpe':>10} {'Sortino':>10} {'Max DD':>10}")
    print("-" * 70)
    for m in metrics:
        print(f"{m['label']:<12} ${m['end_val']:>12,.0f} {m['cagr']:>+9.1%} {m['sharpe']:>10.2f} {m['sortino']:>10.2f} {m['max_dd']:>9.1%}")

    # Create chart
    print("\nCreating comparison chart...")

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(14, 12),
                                    gridspec_kw={'height_ratios': [3, 1]})

    colors = {
        "SPY B&H": "#1f77b4",
        "SSO B&H": "#ff7f0e",
        "UPRO B&H": "#d62728",
        "50-Delta": "#2ca02c",
        "55-Delta": "#17becf",
        "60-Delta": "#9467bd",
        "70-Delta": "#8c564b",
        "80-Delta": "#e377c2",
        "90-Delta": "#7f7f7f",
        "95-Delta": "#bcbd22",
    }

    for label, df in loaded.items():
        color = colors.get(label, "#333333")
        linewidth = 2.5 if label in ["SPY B&H", "80-Delta", "UPRO B&H"] else 1.5
        linestyle = "--" if "B&H" in label and label != "SPY B&H" else "-"
        alpha = 1.0 if label in ["SPY B&H", "80-Delta", "UPRO B&H", "70-Delta"] else 0.7

        ax1.semilogy(df["date"], df["portfolio_value"],
                     label=label, color=color, linewidth=linewidth,
                     linestyle=linestyle, alpha=alpha)

    # Highlight crisis periods
    crisis_periods = [
        ("2020-02-19", "2020-03-23", "COVID", "#ffe6cc"),
        ("2022-01-03", "2022-10-12", "2022 Bear", "#fff2cc"),
    ]
    for start, end, name, color in crisis_periods:
        ax1.axvspan(pd.to_datetime(start), pd.to_datetime(end),
                    alpha=0.3, color=color)

    ax1.set_ylabel("Portfolio Value ($, log scale)", fontsize=12)
    ax1.set_title(f"$100,000 Investment from {START_DATE}: Fair Comparison with UPRO",
                  fontsize=14, fontweight="bold")
    ax1.legend(loc="upper left", fontsize=9, ncol=2)
    ax1.grid(True, alpha=0.3)

    # Bottom panel: Summary table
    ax2.axis("off")
    table_data = []
    headers = ["Strategy", "End Value", "CAGR", "Sharpe", "Sortino", "Max DD"]

    for m in metrics:
        table_data.append([
            m["label"],
            f"${m['end_val']:,.0f}",
            f"{m['cagr']:+.1%}",
            f"{m['sharpe']:.2f}",
            f"{m['sortino']:.2f}",
            f"{m['max_dd']:.1%}",
        ])

    table = ax2.table(cellText=table_data, colLabels=headers,
                      loc="center", cellLoc="center",
                      colColours=["#f0f0f0"] * len(headers))
    table.auto_set_font_size(False)
    table.set_fontsize(9)
    table.scale(1.2, 1.6)

    # Highlight key rows
    for i, m in enumerate(metrics):
        if m["label"] == "80-Delta":
            for j in range(len(headers)):
                table[(i + 1, j)].set_facecolor("#e6ffe6")
        elif m["label"] == "UPRO B&H":
            for j in range(len(headers)):
                table[(i + 1, j)].set_facecolor("#ffe6e6")

    plt.tight_layout()
    output_path = os.path.join(_this_dir, "comparison_from_2009.png")
    plt.savefig(output_path, dpi=150, bbox_inches="tight")
    print(f"\nChart saved to: {output_path}")
    plt.close()


if __name__ == "__main__":
    main()
